src/Entity/Artiste.php
<?php

namespace App\Entity;

use App\Repository\ArtisteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArtisteRepository::class)]
class Artiste
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $civilite = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column(length: 50)]
    private ?string $lastname = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $dateNaiss = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $dateDeces = null;

    #[ORM\ManyToMany(targetEntity: Chant::class, mappedBy: 'auteur')]
    private Collection $artAuteur;

    #[ORM\ManyToMany(targetEntity: Chant::class, mappedBy: 'compositeur')]
    private Collection $artCompositeur;

    public function __construct()
    {
        $this->artAuteur = new ArrayCollection();
        $this->artCompositeur = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->firstname.' '.$this->lastname;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(?string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname(): string
    {
        return $this->lastname.' '.$this->firstname;
    }

    public function getDateNaiss(): ?string
    {
        return $this->dateNaiss;
    }

    public function setDateNaiss(?string $dateNaiss): self
    {
        $this->dateNaiss = $dateNaiss;

        return $this;
    }

    public function getDateDeces(): ?string
    {
        return $this->dateDeces;
    }

    public function setDateDeces(?string $dateDeces): self
    {
        $this->dateDeces = $dateDeces;

        return $this;
    }

    /**
     * @return Collection<int, Chant>
     */
    public function getArtAuteur(): Collection
    {
        return $this->artAuteur;
    }

    public function addArtAuteur(Chant $artAuteur): self
    {
        if (!$this->artAuteur->contains($artAuteur)) {
            $this->artAuteur->add($artAuteur);
            $artAuteur->addAuteur($this);
        }

        return $this;
    }

    public function removeArtAuteur(Chant $artAuteur): self
    {
        if ($this->artAuteur->removeElement($artAuteur)) {
            $artAuteur->removeAuteur($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Chant>
     */
    public function getArtCompositeur(): Collection
    {
        return $this->artCompositeur;
    }

    public function addArtCompositeur(Chant $artCompositeur): self
    {
        if (!$this->artCompositeur->contains($artCompositeur)) {
            $this->artCompositeur->add($artCompositeur);
            $artCompositeur->addCompositeur($this);
        }

        return $this;
    }

    public function removeArtCompositeur(Chant $artCompositeur): self
    {
        if ($this->artCompositeur->removeElement($artCompositeur)) {
            $artCompositeur->removeCompositeur($this);
        }

        return $this;
    }
}

templates/_partials/_footer.html.twig
<!-- Pied de page -->
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4">
    <div class="col-md-4 d-flex align-items-center">
      {# <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      </a> #}
      <span class="mb-3 mb-md-0 text-muted">&copy; 2023 Company, Inc</span>
    </div>

    {# <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
    </ul> #}
  </footer>
</div>

templates/_partials/_nav.html.twig
<!-- Navigation -->
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="{{ path('app_home') }}">Répertoire</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            {# {% if app.user %} #}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_chant_index') }}">Chants</a>
                    </li>
                    {# {% if is_granted('ROLE_ANIM') %} #}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_artiste_index') }}">Artistes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_secli_index') }}">Fiches Secli</a>
                    </li>
                    {# {% endif %} #}
                    {# <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_celebration_index') }}">Célébrations</a>
                    </li> #}
                {# {% if is_granted('ROLE_SUPER_ADMIN') %} #}
                    {# <li class="nav-item">
                        <a class="nav-item nav-link" href="{{ path('app_admin') }}#">Administration</a>
                    </li> #}
                {# {% endif %} #}
                </ul>
                {# <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user mr-2"></i> {{ app.user.fullname }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#"><i class="fas fa-id-card"></i> Mon compte</a>
                            <li><a class="dropdown-item" href="#"><i class="fas fa-key"></i> Mot de passe</a>
                            <li><a class="dropdown-item" href="{{ path('app_logout') }}"><i class="fas fa-sign-in-alt"></i> Se déconnecter</a>
                        </ul>
                    </li>
                </ul> #}
            {# {% else %} #}
                {# <ul class="navbar-nav ms-auto"> #}
                    {# <a class="nav-item nav-link " href="{{ path('app_login') }}"><i class="fas fa-sign-in-alt"></i> Se connecter</a> #}
                {# </ul> #}
            {# {% endif %} #}
        </div>
    </div>
</nav>