src/Entity/Chant.php
<?php

namespace App\Entity;

use App\Repository\ChantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinTable;

#[ORM\Entity(repositoryClass: ChantRepository::class)]
class Chant
{
    use Trait\ChantTrait;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $coteEdit = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $source = null;

    #[ORM\Column(nullable: true)]
    private ?int $secli = null;

    #[ORM\Column]
    private ?bool $ordinaire = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $texte = null;

    #[ORM\ManyToOne(inversedBy: 'chants')]
    private ?Editeur $editeur = null;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'artAuteur')]
    #[JoinTable(name: 'chants_auteurs')]
    private Collection $auteur;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'artCompositeur')]
    #[JoinTable(name: 'chants_compositeurs')]
    private Collection $compositeur;

    public function __construct()
    {
        $this->auteur = new ArrayCollection();
        $this->compositeur = new ArrayCollection();
    }

    public function getAffich(): ?string
    {
        if ($this->coteEdit) {
            if (str_starts_with($this->coteEdit, 'IEV')) {
                return $this->titre.' ('.$this->coteEdit.')';
            }
        }

        if (!$this->cote) {
            if (!$this->coteNew) {
                if (!$this->coteEdit) {
                    return $this->titre;
                } else {
                    return $this->titre.' ('.$this->coteEdit.')';
                }
            } elseif (!$this->coteEdit) {
                return $this->titre.' ('.$this->coteNew.')';
            } else {
                return $this->coteEdit;
            }
        } else {
            return $this->titre.' ('.$this->cote.')';
        }

        return '';
    }

    public function getCoteEdit(): ?string
    {
        return $this->coteEdit;
    }

    public function setCoteEdit(?string $coteEdit): self
    {
        $this->coteEdit = $coteEdit;

        return $this;
    }

    public function getSource(): ?string
    {
        return $this->source;
    }

    public function setSource(?string $source): self
    {
        $this->source = $source;

        return $this;
    }

    public function getSecli(): ?int
    {
        return $this->secli;
    }

    public function setSecli(?int $secli): self
    {
        $this->secli = $secli;

        return $this;
    }

    public function isOrdinaire(): ?bool
    {
        return $this->ordinaire;
    }

    public function setOrdinaire(bool $ordinaire): self
    {
        $this->ordinaire = $ordinaire;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(?string $texte): self
    {
        $this->texte = $texte;

        return $this;
    }

    public function getEditeur(): ?Editeur
    {
        return $this->editeur;
    }

    public function setEditeur(?Editeur $editeur): self
    {
        $this->editeur = $editeur;

        return $this;
    }

    /**
     * @return Collection<int, Artiste>
     */
    public function getAuteur(): Collection
    {
        return $this->auteur;
    }

    public function addAuteur(Artiste $auteur): self
    {
        if (!$this->auteur->contains($auteur)) {
            $this->auteur->add($auteur);
        }

        return $this;
    }

    public function removeAuteur(Artiste $auteur): self
    {
        $this->auteur->removeElement($auteur);

        return $this;
    }

    /**
     * @return Collection<int, Artiste>
     */
    public function getCompositeur(): Collection
    {
        return $this->compositeur;
    }

    public function addCompositeur(Artiste $compositeur): self
    {
        if (!$this->compositeur->contains($compositeur)) {
            $this->compositeur->add($compositeur);
        }

        return $this;
    }

    public function removeCompositeur(Artiste $compositeur): self
    {
        $this->compositeur->removeElement($compositeur);

        return $this;
    }
}

src/Form/ChantType.php
<?php

namespace App\Form;

use App\Entity\Chant;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class, [
                'required' => true,
            ])
            ->add('annee', IntegerType::class, [
                'required' => false,
            ])
            ->add('cote', TextType::class, [
                'required' => false,
            ])
            ->add('coteNew', TextType::class, [
                'required' => false,
            ])
            ->add('coteEdit', TextType::class, [
                'required' => false,
            ])
            ->add('snpls', IntegerType::class, [
                'required' => false,
            ])
            ->add('source', TextType::class, [
                'required' => false,
            ])
            ->add('ordinaire', CheckboxType::class, [
                'label' => false,
                'required' => false,
            ])
            ->add('texte', CKEditorType::class)
            ->add('auteur', ArtisteAutocompleteField::class)
            ->add('compositeur', ArtisteAutocompleteField::class)
            ->add('editeur', EditeurAutocompleteField::class, [
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Chant::class,
        ]);
    }
}

src/Controller/ChantController.php
<?php

namespace App\Controller;

use App\Entity\Chant;
use App\Entity\Secli;
use App\Form\ChantType;
use App\Repository\ChantRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/chant')]
class ChantController extends AbstractController
{
    public function __construct(
        private ChantRepository $chantRepository,
        private EntityManagerInterface $em,
    ) {
    }

    #[Route('/', name: 'app_chant_index', methods: ['GET'])]
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $chants = $paginator->paginate(
            $this->chantRepository->findAllOrderTitre(),
            $request->query->getInt('page', 1),
            12
        );

        return $this->render('chant/index.html.twig', [
            'chants' => $chants,
        ]);
    }

    #[Route('/new', name: 'app_chant_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $chant = new Chant();
        $form = $this->createForm(ChantType::class, $chant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->chantRepository->save($chant, true);

            return $this->redirectToRoute('app_chant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('chant/new.html.twig', [
            'chant' => $chant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_chant_show', methods: ['GET'])]
    public function show(Chant $chant): Response
    {
        return $this->render('chant/show.html.twig', [
            'chant' => $chant,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_chant_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Chant $chant): Response
    {
        $form = $this->createForm(ChantType::class, $chant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->chantRepository->save($chant, true);

            return $this->redirectToRoute('app_chant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('chant/edit.html.twig', [
            'chant' => $chant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_chant_delete', methods: ['POST'])]
    public function delete(Request $request, Chant $chant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$chant->getId(), $request->request->get('_token'))) {
            $this->chantRepository->remove($chant, true);
        }

        return $this->redirectToRoute('app_chant_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id<\d+>}/import', name: 'app_chant_import')]
    public function import(Secli $secli, Request $request): Response
    {
        $chant = new Chant();

        $chant->setTitre(strtolower($secli->getTitre()));
        $chant->setCote($secli->getCote());
        $chant->setCotenew($secli->getCoteNew());
        $chant->setAnnee($secli->getAnnee());
        if ('1900' == $secli->getAnnee()) {
            $chant->setAnnee(null);
        }
        $chant->setSnpls($secli->getSnpls());
        $chant->setSecli($secli->getFiche());

        $secli->setImporte(true);

        $form = $this->createForm(ChantType::class, $chant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($chant);
            $this->em->flush();

            $this->em->persist($secli);

            return $this->redirectToRoute('app_secli_index');
        }

        return $this->render('chant/import.html.twig', [
            'secli' => $secli,
            'chant' => $chant,
            'form' => $form,
        ]);
    }
}

templates/chant/_delete_form.html.twig
<form method="post" action="{{ path('app_chant_delete', {'id': chant.id}) }}" onsubmit="return confirm('Êtes-vous sûr(e) de vouloir supprimer ce chant ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ chant.id) }}">
    <button class="btn btn-sm btn-danger">Supprimer</button>
</form>

templates/chant/_fiche.html.twig
<!-- Modal -->
<div class="modal" id="textModal{{ chant.id }}" tabindex="-1" aria-labelledby="textModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-11">
                            <h1 class="modal-title fs-3" id="textModalLabel">{{ chant.affich }}</h1>
                        </div>
                        <div class="col-md-1">
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 fs-6">
                            {% if chant.coteNew %}
                                Nouvelle cote : {{ chant.coteNew }}
                            {% endif %}
                        </div>
                        <div class="col-md-6 ms.auto fs-6">
                            {% if chant.coteEdit %}
                                Cote Éditeur : {{ chant.coteEdit }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 fs-6"><strong>Auteur(s) :</strong><br>
                            {% for auteur in chant.auteur %}
                                {{ auteur.firstname }} {{ auteur.lastname }}
                                {% if loop.first and not loop.last %}<br>{% endif %}
                            {% endfor %}
                        </div>
                        <div class="col-md-6 fs-6"><strong>Compositeur(s) :</strong><br>
                            {% for compositeur in chant.compositeur %}
                                {{ compositeur.firstname }} {{ compositeur.lastname }}
                                {% if loop.first and not loop.last %}<br>{% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            {% if chant.texte %}
                <div class="modal-body">
                    <div class="container-fluid">
                        <div class="row">
                            {{ chant.texte|raw }}
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="modal-body">
                    <div class="container-fluid">
                        <div class="row">
                            <em>Texte à enregistrer</em>
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="modal-footer">
                <div class="container-fluid">
                    {% if chant.editeur %}
                        <div class="row">
                            <div class="col-md-11 fs-6">Éditeur :
                                {{ chant.editeur }}
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

templates/chant/_form.html.twig
{{ form_start(form) }}
    <div class="row">
        <div class="col-4">
            {{ form_row(form.titre, {
                label: 'Titre'
            }) }}
        </div>
        <div class="col-2">
            {{ form_row(form.annee, {
                label: 'Année'
            }) }}
        </div>
        <div class="col-2">
            {{ form_row(form.snpls, {
                label: 'Promotion SNPLS'
            }) }}
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            {{ form_row(form.ordinaire, {
                label: 'Ordinaire ?'
            }) }}
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            {{ form_row(form.cote, {
                label: 'Cote'
            }) }}
        </div>
        <div class="col-2">
            {{ form_row(form.coteNew, {
                label: 'Cote (nouvelle)'
            }) }}
        </div>
        <div class="col-2">
            {{ form_row(form.coteEdit, {
                label: 'Cote Editeur'
            }) }}
        </div>
        <div class="col-6">
            {{ form_row(form.source, {
                label: 'Source'
            }) }}
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            {{ form_row(form.auteur, {
                label: 'Auteur(s)'
            }) }}
            {{ form_row(form.compositeur, {
                label: 'Compositeur(s)'
            }) }}
            {{ form_row(form.editeur, {
                label: 'Editeur'
            }) }}
        </div>
        <div class="col-6">
            {{ form_row(form.texte, {
                label: 'Paroles'
            }) }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <a href="{{ path('app_chant_index') }}" class="btn btn-sm btn-primary">Retour</a>
            <button class="btn btn-sm btn-success">Enregistrer</button>
        </div>
    </div>
{{ form_end(form) }}

templates/chant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition d'un chant{% endblock %}

{% block body %}
    <div class="container mt-2">
        <h2>Chants</h2>
        {{ include('chant/_form.html.twig') }}
    </div>
{% endblock %}

templates/chant/import.html.twig
{% extends 'base.html.twig' %}

{% block title %}Import{% endblock %}

{% block body %}
    <div class="container mt-2">
        <h3>Import du chant : {{ secli.titre|lower|capitalize }} ({{ secli.cote }})</h3>
        <hr>
        {{ form_start(form) }}
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th scope="col">Secli</th>
                        <th scope="col"></th>
                        <th scope="col">Import</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ secli.titre }}</td>
                        <td>Titre</td>
                        <td>{{ form_widget(form.titre) }}</td>
                    </tr>
                    <tr>
                        <td>{{ secli.cote }}</td>
                        <td>Cote</td>
                        <td>{{ form_widget(form.cote) }}</td>
                    </tr>
                    <tr>
                        <td>{{ secli.coteNew }}</td>
                        <td>Nouvelle Cote</td>
                        <td>{{ form_widget(form.coteNew) }}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>Cote éditeur</td>
                        <td>{{ form_widget(form.coteEdit) }}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>Source</td>
                        <td>{{ form_widget(form.source) }}</td>
                    </tr>
                    <tr>
                        <td>{{ secli.auteur }}</td>
                        <td>Auteur(s)</td>
                        <td>{{ form_widget(form.auteur) }}</td>
                    </tr>
                    <tr>
                        <td>{{ secli.compositeur }}</td>
                        <td>Compositeur(s)</td>
                        <td>{{ form_widget(form.compositeur) }}</td>
                    </tr>
                    <tr>
                        <td>{{ secli.annee }}</td>
                        <td>Année</td>
                        <td>{{ form_widget(form.annee) }}</td>
                    </tr>
                    <tr>
                        <td>{{ secli.snpls }}</td>
                        <td>Promotion SNPLS</td>
                        <td>{{ form_widget(form.snpls) }}</td>
                    </tr>
                    <tr>
                        <td>{{ secli.editeur }}</td>
                        <td>Éditeur</td>
                        <td>{{ form_widget(form.editeur) }}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>Ordinaire ?</td>
                        <td>{{ form_widget(form.ordinaire) }}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>Paroles</td>
                        <td>{{ form_widget(form.texte) }}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>
                            <button type="submit" class="btn btn-sm btn-primary">{{ button_label|default('Sauvegarder') }}</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/chant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Répertoire{% endblock %}

{% block body %}
    <div class="container mt-2">
        <h2>Chants</h2>
        <table class="table table-hover table-sm mt-4">
            <thead>
                <tr>
                    <th scope="col">Titre</th>
                    <th scope="col">Cote</th>
                    <th scope="col">Cote Éditeur</th>
                    <th scope="col">Année</th>
                    <th scope="col">Auteur(s)</th>
                    <th scope="col">Compositeur(s)</th>
                    <th scope="col">Éditeur</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for chant in chants %}
                <tr data-bs-toggle="modal" data-bs-target="#textModal{{ chant.id }}">
                    <td scope="row">{{ chant.titre }}</td>
                    <td scope="row">{{ chant.cote }}
                        {% if chant.coteNew %}
                            <br><span class="badge bg-secondary">{{ chant.coteNew }}</span>
                        {% endif %}
                    </td>
                    <td scope="row">{{ chant.coteEdit }}</td>
                    <td scope="row">{{ chant.annee }}</td>
                    <td scope="row">
                        {% for auteur in chant.auteur %}
                            {{ auteur.firstname }} {{ auteur.lastname }}<br>
                        {% endfor %}
                    </td>
                    <td scope="row">
                        {% for compositeur in chant.compositeur %}
                            {{ compositeur.firstname }} {{ compositeur.lastname }}<br>
                        {% endfor %}
                    </td>
                    {% if chant.editeur %}
                        <td scope="row">{{ chant.editeur.nom }}</td>
                    {% else %}
                        <td scope="row">-</td>
                    {% endif %}
                    <td>
                        {% include 'chant/_fiche.html.twig' %}
                        <a href="{{ path('app_chant_edit', {id: chant.id}) }}" class="btn btn-sm btn-success" role="button">Editer</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <div class="col-auto me-auto">
                <div class="pagination">
                    {{ knp_pagination_render(chants, null, {}, {
                        'align': 'center',
                        'size': 'small',
                        'rounded': true,
                    }) }}
                </div>
            </div>
            <div class="col-auto ms-auto">
                <a href="{{ path('app_chant_new') }}" class="btn btn-sm btn-primary">Nouveau chant</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/chant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau chant{% endblock %}

{% block body %}
    <div class="container mt-2">
        <h2>Nouveau chant</h2>

        {{ include('chant/_form.html.twig') }}

        <a href="{{ path('app_chant_index') }}" class="btn btn-sm btn-primary">Retour</a>
    </div>
{% endblock %}

templates/chant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chant{% endblock %}

{% block body %}
    <div class="container mt-2">
        <h2>Chant</h2>

        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ chant.id }}</td>
                </tr>
                <tr>
                    <th>Titre</th>
                    <td>{{ chant.titre }}</td>
                </tr>
                <tr>
                    <th>Annee</th>
                    <td>{{ chant.annee }}</td>
                </tr>
                <tr>
                    <th>Cote</th>
                    <td>{{ chant.cote }}</td>
                </tr>
                <tr>
                    <th>CoteNew</th>
                    <td>{{ chant.coteNew }}</td>
                </tr>
                <tr>
                    <th>CoteEdit</th>
                    <td>{{ chant.coteEdit }}</td>
                </tr>
                <tr>
                    <th>Snpls</th>
                    <td>{{ chant.snpls }}</td>
                </tr>
                <tr>
                    <th>Source</th>
                    <td>{{ chant.source }}</td>
                </tr>
                <tr>
                    <th>Secli</th>
                    <td>{{ chant.secli }}</td>
                </tr>
                <tr>
                    <th>Texte</th>
                    <td>{{ chant.texte }}</td>
                </tr>
            </tbody>
        </table>

        <a href="{{ path('app_chant_index') }}" class="btn btn-sm btn-primary">Retour</a>

        <a href="{{ path('app_chant_edit', {'id': chant.id}) }}" class="btn btn-sm btn-warning">Éditer</a>

        {{ include('chant/_delete_form.html.twig') }}
    </div>
{% endblock %}